version: "3.8"
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: python_visualaccess
    environment:
      VSAC_REDIS: "redis://host.docker.internal:6379"
      VSAC_PGSQL: "Host=host.docker.internal;Port=5432;Database=visualaccessdb;Username=user;Password=P@ssword123"
    ports:
      - "50051:50051"
    volumes:
      - ..:/app
    command: /bin/bash -c "pip install -r requirements.txt && python /app/server.py"
